[package]
name = "boat3_server"
version = "0.1.0"
edition = "2024"

[dependencies]
anstyle = "1.0.13"
axum = "0.8.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_repr = "0.1.20"
tokio = { version = "1.48.0", features = ["full"] }
